# LA BIBLIA - Verdantia (Normas Inquebrantables)

## Reglas de Oro
1. **Acceso Local:** Cuando se solicite "acceso local", iniciar únicamente el servidor en `localhost:3000`. **NUNCA** iniciar túneles (ngrok, pinggy, etc.) a menos que se pida de forma explícita.
2. **Canal de Despliegue Exclusivo (Modo Autónomo por Chat):** El asistente tiene el mandato y permiso total para asumir el control y automatizar el proceso de subida a producción. Si el usuario da la orden explícita mediante palabras clave como "SUBE A PRODUCCION", "sincroniza en GitHub" (o incluso variantes con errores de teclado como "SU(BE A PRODUCCION"), el agente ejecutará el despliegue íntegramente desde su propia terminal. Esto se hace para detectar y corregir cualquier error de código que surja durante la compilación (`npm run build`) en tiempo real.
   * **Integración con la Web:** Los botones del panel web están diseñados para copiar esta orden al portapapeles. El usuario solo debe pegar el comando en el chat para delegar la tarea al agente de forma segura.
   * **Protocolo de Despliegue:** Aunque lo haga el agente, se debe seguir el orden estricto de documentar en la Guía de Usuario, incrementar y estampar versión, compilar (corrigiendo fallos autónomamente si los hay), hacer commit, push a Git y desplegar en Firebase.
3. **Compatibilidad Next.js:** Prestar especial atención a las APIs y la estructura de archivos de la versión instalada de Next.js. Consultar los manuales de `node_modules/next/dist/docs/` ante cualquier cambio para evitar el uso de importaciones o funciones obsoletas.
4. **Refresco Automático y Efectivo (MANDATO INQUEBRANTABLE):** El asistente tiene la **OBLIGACIÓN ABSOLUTA E INELUDIBLE** de actualizar la página del navegador de forma automática cada vez que finalice una tarea o instrucción. **Cualquier cambio aplicado que no sea visualizado instantáneamente por el usuario es un FRACASO CRÍTICO.**
   - Si se modifican componentes React (`.tsx`), Next.js aplicará Hot Reload automáticamente.
   - Si Next.js no detecta el cambio o se editan archivos estáticos fuera del árbol principal (ej. `.md`, `.json`, `next.config.js`), el asistente **DEBE** forzar el refresco alterando el archivo principal implicado (ej. añadiendo un comentario temporal).
   - Si la caché de Turbopack se enquista y el usuario reporta que no ve los cambios, el asistente aplicará la purga nuclear de inmediato sin preguntar: `rm -r .next` y reiniciar `npm run dev`. ¡CERO EXCUSAS!
5. **Control de Copias de Seguridad (GitHub) - [¡REGLA ABSOLUTA DE CUMPLIMIENTO CRÍTICO!]:** **NUNCA** extraerás, restaurarás, revertirás ni descargarás una copia de seguridad o rama de GitHub de forma espontánea o autónoma. Está **TERMINANTEMENTE PROHIBIDO** hacer esto sin permiso expreso. Si por motivos de fuerza mayor consideras necesario recurrir a Git/GitHub para restaurar código, **DEBES** pedir autorización explícita al usuario, explicando detalladamente los motivos y riesgos antes de ejecutar cualquier comando. Hacedlo de forma autónoma es un fallo imperdonable y motivo de parada inmediata.
6. **Navegación Local y Pruebas de Navegador:** **NUNCA** realizarás navegación local ni abrirás/utilizarás el subagente de navegación del navegador (browser subagent) para comprobar páginas, realizar capturas de pantalla o realizar pruebas automáticas sin pedir permiso explícito al usuario antes de ejecutar dicha acción.
7. **Estándar de Dashboard de Muestra de Datos:** Todo dashboard destinado a listar o mostrar colecciones de datos (ej. catálogo de especies) debe basarse estrictamente en la ruta `/dashboard/admin/especies` y cumplir obligatoriamente estas características:
   - **Ancho Completo:** La vista debe ocupar el 100% del ancho (`width: '100%'`), sin restricciones de `maxWidth` ni centrados.
   - **Subheader Global:** Debe incluir un bloque superior con fondo degradado (`linear-gradient`) pertinente al módulo, conteniendo el Título (con Emoji) a la izquierda, y los botones de acción principal (Ej. `➕ Nuevo`) a la derecha. Los filtros rápidos (tags/píldoras) irán integrados en la parte inferior de este subheader.
   - **Carga sin Flickering (Overlay):** Queda prohibido desmontar la tabla al cargar o filtrar datos. Se debe usar un contenedor `position: 'relative'` y superponer un Overlay absoluto semitransparente (`rgba(255,255,255,0.65)`) con un spinner circular, mientras la tabla reduce su opacidad al 60%.
   - **Tabla Zebra y Botonera Estandarizada:** Las filas alternarán colores de fondo (`white` y `#f8fafc`). La columna de acciones a la derecha tendrá botones consistentes con sus códigos de color: Editar (Gris/Blanco), Inhabilitar (Amarillo), Eliminar (Rojo), Reactivar (Verde).
   - **Columna Fija (Sticky):** La primera columna de la tabla (normalmente el icono, emoji o foto identificativa) debe mantenerse permanentemente visible al hacer scroll horizontal. Esto es **obligatorio** y se logra aplicando `position: 'sticky', left: 0, zIndex: 1` a dicha columna, asegurando que el resto del registro se desplace por detrás de ella. La celda contenedora (`<td>`) debe tener estrictamente `width: '80px', minWidth: '80px', textAlign: 'center', padding: '8px'`.
   - **Tamaño Estándar de Miniatura:** El contenedor `div` que envuelve a la foto, emoji o bandera dentro de esta primera columna debe ser **cuadrado**, midiendo obligatoriamente `56px` de ancho por `56px` de alto (`width: '56px', height: '56px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden'`).
   - **Acceso Rápido de Edición:** La foto, emoji o icono de la primera columna (columna fija) debe ser interactiva (`cursor: pointer`) y al hacer clic sobre ella debe abrir o redirigir al formulario de edición del registro correspondiente. El botón oficial de "Editar" de la columna de acciones de la derecha se debe mantener intacto como entrada secundaria.
   - **Conteo en Tags/Filtros:** Los tags o píldoras de filtros rápidos deben mostrar obligatoriamente a cuántos registros representan (ej. "Activos (4)", "Todos (12)").
   - **Ordenación en Encabezados:** Los títulos de los encabezados de las tablas (headers) deben permitir la ordenación (alfabética o numérica) ascendente/descendente de los registros al hacer clic en ellos (mostrando obligatoriamente los indicadores visuales 🔼 o 🔽). Además, el estado de ordenación activo se debe persistir utilizando `sessionStorage` para mantener la misma vista si el usuario sale y vuelve a entrar al dashboard. Esto se aplica a cada columna que sea susceptible de ordenación.
8. **Estándar de Dashboard de Edición de Datos:** Toda ruta de edición de formularios (ej. `/dashboard/admin/especies/[id]`) es el estándar maestro de edición y debe seguir obligatoriamente estos patrones:
   - **Ancho Completo:** La vista debe ocupar el 100% del ancho (`width: '100%'`), sin restricciones de `maxWidth` ni centrados.
   - **Navegación Hierárquica Superior:** Doble botonera alineada a la izquierda y situada en lo alto del DOM: `🏠 Volver al Inicio` y `🔙 Volver a [Listado Global]`. Quedan prohibidos los botones de 'Volver' redundantes a pie de página.
   - **Subheader Contextual y Autoguardado (Estructura Estándar de Dos Líneas):** Debajo de la navegación mostrará un subheader con fondo degradado pertinente al módulo, con un padding de `12px 20px` y border radius de `14px` (altura estándar compacta). Su estructura se dividirá en exactamente dos bloques alineados horizontalmente (con `display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap'`):
      - **Bloque Izquierdo (Título):** Título de edición (con Emoji y Nombre principal, ej. `👤 Juan Illueca Sanchis`) y una pequeña descripción de contexto (`✏️ Editar [Entidad] · ID del Registro: [ID]`) debajo de este.
      - **Bloque Derecho (Datos y Autoguardado):** Los datos adicionales del registro (como `@nombreUsuario`, email, y pastillas/pills de estado de roles, planes, etc. de tamaño reducido `padding: '2px 6px'`, `fontSize: '0.7rem'`) alineados horizontalmente, seguidos a la derecha por el indicador visual de autoguardado automático (Auto-Save con debounce: `⏳ Guardando...` / `✅ Guardado` con padding `3px 8px`, `fontSize: '0.74rem'`). Todo este bloque derecho debe ocupar el espacio restante, estar centrado horizontalmente en el espacio disponible (con `flex: 1` y `justifyContent: 'center'`) y centrado verticalmente en el encabezado.
   - **Estado Global/Activo en Primer Lugar:** El control o interruptor del estado global de la entidad (`Activo / Inactivo` o similar) debe colocarse obligatoriamente al inicio del formulario, situado justo debajo del Subheader contextual y por encima del Hero Carousel o de las pestañas de navegación, asegurando que la visibilidad/activo del elemento sea la primera interacción del formulario.
   - **Pestañas Controladas por CSS:** Queda tajantemente prohibido usar renderizado condicional de React para las pestañas de contenido. Todas las pestañas deben estar renderizadas siempre en el DOM y se ocultarán exclusivamente mediante CSS (`display: none / block` o `grid`) para precargar los datos en segundo plano sin parpadeos.
   - **Multimedia Segregado:** Prohibido agrupar fotos y documentos bajo una pestaña "Adjuntos". Obligatorio separarlo en pestañas independientes `📷 Fotos` y `📄 PDFs`, instanciando siempre el gestor `VariedadMediaManager`.
   - **Edición en Línea (Grids):** Cualquier colección secundaria anidada debe gestionarse a través de listas/tablas editables en línea sin requerir ventanas modales externas.
9. **Estándar Fotográfico y Multimedia (Hero Carousel & Galerías):** Cualquier módulo que gestione fotografías en los dashboards de edición debe cumplir esta arquitectura estricta:
   - **Hero Carousel (Encabezado Visual):** Situado debajo del Subheader contextual. Debe tener un fondo degradado basado en el color vibrante (extraído por IA). Contendrá la Foto Principal (Hero) a tamaño `180px x 220px` (proporción 3:4) aplicando todos los metadatos JSON de encuadre/zoom/brillo.
     - **Diseño del contenedor (cero textos):** Queda prohibido añadir bloques de texto, contadores numéricos de fotos o títulos redundantes dentro de este carrusel.
     - **Caso de 1 sola foto:** Se renderizará únicamente el Hero de `180px x 220px` a la izquierda. La zona derecha del degradado quedará completamente vacía (sin textos ni placeholders).
     - **Sin badges en Hero:** Queda prohibido renderizar etiquetas absolutas de "⭐ Portada" o "Principal" superpuestas sobre la imagen Hero del carrusel.
   - **Miniaturas Apiladas (Verticales):** Al lado de la foto Hero, se apilarán **verticalmente** un máximo de 3 miniaturas de `52px x 70px`. No heredarán el zoom del Hero para no cortar caras (usarán encuadre neutral `cover`). Su interactividad se marca solo con hover (borde morado `#8b5cf6` y escala), sin añadir textos redundantes como "Haz clic para cambiar".
     - **Drag & Drop en Carrusel:** El contenedor Hero actuará como zona drop (borde discontinuo verde al arrastrar). Al arrastrar cualquier miniatura sobre él, se marcará automáticamente como portada. También se permite reordenar las miniaturas entre sí mediante arrastre.
   - **Sincronización Inmediata:** Cualquier acción en la galería inferior (añadir, borrar, reordenar) disparará el callback `onMediaChange` que actualizará automáticamente el Hero Carousel sin recargas de página.
   - **Galería (Pestaña Fotos):** Incorpora el motor Dropzone, renderización instantánea con BlurHash y botones de acción unificados (Estrella=Portada, Lápiz=Editar, X=Eliminar).
     - **Ubicación del Dropzone (Inline Card):** Queda prohibido añadir un Dropzone de gran tamaño por separado de la rejilla de fotos. El Dropzone debe instanciarse obligatoriamente como una tarjeta inline (`.custom-file-upload.drop-zone.inline-drop-zone`) integrada en la rejilla de fotos (`.gallery`), situada inmediatamente al lado de la última foto cargada.
     - **Visibilidad Dinámica del Dropzone:** Este Dropzone inline solo se mostrará si no se ha alcanzado el límite máximo de 4 fotografías. Si el contador llega al límite de 4, el dropzone desaparecerá por completo de la rejilla.
     - **Arrastre en Rejilla:** Las fotos de la galería deben admitir reordenación directa arrastrándolas entre sí.
     - **Filtros en Rejilla:** Las imágenes miniatura en la rejilla de fotos de la galería deben aplicar el mismo estilo, brillo y contraste dinámicos de sus metadatos (`resumen.profile_style`).
   - **Editor Visual Estándar:** El modal de edición fotográfica forzará la proporción 3:4 y soportará Drag-to-Pan (arrastre libre) y sliders de Zoom, Brillo y Contraste, persistiendo los datos en un objeto JSON (`resumen`). Contará con selector desplegable de 9 filtros estandarizados (con preview dinámico en vivo en el modal), botón "Auto Color" y "Smart Save".
     - **Dependencia y Estilos CSS:** Es **obligatorio** heredar y utilizar las clases visuales de `EspecieForm.css` (`photo-editor-overlay`, `photo-editor-content`, `photo-editor-header`, `photo-editor-body`, `photo-editor-preview-container`, `photo-editor-preview-mask`, `photo-editor-image`, `photo-editor-hint`, `photo-editor-controls`, `editor-control-group`, `photo-editor-footer`). Queda estrictamente **prohibido** inventar modales ad-hoc con estilos inline o Tailwind.
     - **Estructura Interna del Modal:** El cuerpo del modal (`.photo-editor-body`) se dividirá en: (1) **Contenedor Preview (izquierda):** `.photo-editor-preview-container` que envuelve la máscara de recorte de 3:4 (`.photo-editor-preview-mask` y la imagen `.photo-editor-image`), con un indicador `.photo-editor-hint` debajo. (2) **Contenedor Controles (derecha):** `.photo-editor-controls` con los sliders de Zoom, Brillo y Contraste colocados dentro de sus respectivos `.editor-control-group`, seguidos por los botones de acción rápida, el selector de filtros de estilo y la descripción de alt text SEO.
   - **Límite Estricto de Fotos:** El sistema global de fotos (como las Especies Globales) admite un máximo estricto de **4 fotografías** en total (1 Hero + 3 miniaturas). Este límite es una restricción básica de la arquitectura del diseño y aplica obligatoriamente sin importar los permisos de superadministrador.
10. **Estándar de la Guía IA (Wizards Secuenciales de Datos - 🧙‍♂️):** Todo proceso de recolección de datos paso a paso (ej. Guía IA de Semillas, Onboarding) es una **Guía IA**. Se diferencia radicalmente del Asistente IA en que la Guía *te lleva de la mano* pidiendo datos, mientras que el Asistente busca información por ti. Debe cumplir estas directrices organizativas y de diseño:
   - **Diseño del Botón Llamador (Magical Purple):** Para diferenciarlo de botones normales o de Asistentes IA, el botón que abre una Guía IA debe mostrar obligatoriamente el emoji del mago `🧙‍♂️` envuelto en un span (`<span style={{ fontSize: '1.25rem' }}>🧙‍♂️</span> Guía IA de...`). Tendrá fondo degradado púrpura (`linear-gradient(135deg, #8b5cf6, #6d28d9)`), texto blanco, borde semitransparente, sombra morada y estará en un contenedor flex alineado.
   - **Flujo en Cascada (Cascading Flow):** Queda prohibida la navegación por "páginas" aisladas. A medida que el usuario avanza, el paso anterior debe colapsar visualmente en un bloque de resumen (con check verde `✅`, fondo suave y botón de `Cambiar`). El nuevo paso activo se renderizará debajo, ligeramente sangrado, creando una jerarquía visual continua.
   - **Selectores Visuales (Cards) y Emojis:** Las opciones jamás deben ser `<select>` nativos genéricos. Se usarán tarjetas interactivas en `grid`, con hover effects (elevación y borde) y siempre acompañadas de Emojis o fotos.
   - **Indicadores y Explicaciones:** El Subheader del modal debe indicar el paso actual (`Paso X de Y`). Si se solicitan datos complejos, se usarán bloques explicativos (ej. `¿Por qué pedimos esto?` en cajas con borde izquierdo coloreado).
   - **Confirmación y Éxito:** El último paso debe ser un resumen visual de lo seleccionado. Al confirmar, mostrar pantalla de éxito con Emoji gigante (ej. `🎉`) antes de que el modal se cierre solo mediante un `setTimeout`.
11. **Restauración de Estado (Botón Volver):** Al entrar a un dashboard, si volvemos a salir de él por medio del botón de vuelta atrás que está en la parte superior encima del encabezado, volveremos al sitio donde estábamos; si era un desplegable o fila expandida, esta estará desplegada, los filtros y pestañas activos se mantendrán seleccionados, el scroll se restaurará a su posición anterior, y el foco visual y/o de teclado irá exactamente al mismo sitio (resaltando la fila o elemento interactuado). Usa `sessionStorage` y `useEffect` en Next.js para persistir el scroll, filtros activos, foco y los estados `isExpanded` / `showDetalle`. Cualquier acceso directo desde el desplegable del menú lateral del superadministrador (por ejemplo, al entrar a la sección de Análisis de Dashboard) se considerará una entrada limpia y se deben anular y limpiar los filtros cargándolos en su estado inicial por defecto (ej. 'all').
12. **Protocolo de Despliegue a Producción:** Antes de ejecutar comandos de despliegue a producción, es OBLIGATORIO: (1) Incrementar la versión en package.json. (2) Actualizar la fecha/hora y versión visible en la landing page (src/app/page.tsx). NUNCA desplegar sin hacer el bump de versión antes.
13. **Protocolo de Refactorizacion Completa de Dashboards:** Cuando se refactoriza un dashboard monolítico (>500 líneas), la refactorización DEBE hacerse en un ÚNICO paso completo, sin medias tintas. El resultado final OBLIGATORIO es un page.tsx de menos de 150 líneas que solo contenga orquestación. El proceso completo es:
   - **Paso 1 - Hooks (lógica de negocio):** Extraer TODO el estado y los handlers a hooks personalizados en una carpeta hooks/ adyacente al page.tsx. Cada dominio funcional tiene su propio hook (ej. usePendientes.ts, useRechazos.ts, usePhotoEditor.ts).
   - **Paso 2 - Componentes (JSX):** Extraer TODOS los bloques de JSX de más de 20 líneas a componentes reutilizables en una carpeta components/ adyacente. Esto incluye: tarjetas de usuario, modales de confirmación, overlays de foto (lightbox), editores visuales, cabeceras, paneles de tabs. NINGÚN bloque JSX extenso puede quedarse inline en el page.tsx.
   - **Paso 3 - Servicios (API):** Extraer todas las llamadas fetch() a un archivo de servicio services/[nombre]Api.ts. El page.tsx y los hooks NO deben contener fetch() directos.
   - **Paso 4 - page.tsx final:** El page.tsx resultante debe ser EXCLUSIVAMENTE un orquestador: importa hooks, importa componentes y los ensambla. Cero lógica de negocio, cero fetch(), cero bloques JSX extensos inline.
   - **Verificación:** Tras la refactorización, el page.tsx debe tener menos de 150 líneas. Si tiene más, la refactorización está INCOMPLETA.
   - **Actualización del contador:** Después de refactorizar, actualizar el número de líneas correspondiente en la tabla de Análisis de Código de mantenimiento/page.tsx para que refleje el valor real.
14. **Marca de Agua y SEO en Imágenes (MANDATO SEO Y MARCA):** Todas las imágenes del blog, galerías o generadas por IA deben llevar de manera obligatoria la marca de agua translúcida de 'VERDANTIA' en la esquina inferior derecha. Asimismo, es imperativo que cada imagen disponga de descripciones de posicionamiento SEO (atributos `alt` y `title` detallados) tanto en la base de datos (dentro del JSON de contenido o campos dedicados) como en el renderizado del código para asegurar un correcto posicionamiento orgánico.
15. **Estándar de Artículos de Blog Generados por IA (AI Blog Standard):** Todo artículo de blog que sea generado mediante los asistentes de Inteligencia Artificial del sistema (por ejemplo, en base a especies, labores o documentos cargados) debe estructurarse rigurosamente bajo el estándar modular definido en `BLOG_STANDARD.md` y `generate-blog/route.ts`. Esto incluye:
    - **Estructura en Bloques Obligatorios:** Encabezado (título interrogativo SEO, resumen, tags, autor y fecha), Ficha Rápida (grid 2x3 con exactamente 6 métricas clave e iconos), Introducción (máx 100 palabras con gancho), Secciones alternadas (H2 + Markdown + fotos alineadas a la derecha o izquierda), Caja de Consejos (con fondo ámbar y borde izquierdo naranja) y un bloque CTA con botones de acción.
    - **Imágenes del Pipeline:** Generación de exactamente 3 imágenes mediante Imagen 4.0, aplicando obligatoriamente el redimensionamiento, conversión a formato WebP/PNG optimizado, marca de agua en la esquina inferior derecha y almacenamiento en Firebase Storage vinculando la metadata en `datosadjuntos`.
    - **Reglas de Redacción:** Párrafos concisos de máximo 3 líneas (sin paja), uso de negritas para destacar conceptos y datos numéricos exactos (temperaturas, marcos de plantación, etc.), manteniendo un tono cercano, profesional y agronómico.
16. **Diseño Responsive para Dashboards:** Al diseñar y desarrollar dashboards y formularios, se tendrá siempre en cuenta el concepto de diseño responsivo. Queda prohibido diseñar interfaces exclusivas para resoluciones de escritorio; cualquier formulario o panel de visualización de datos debe ser perfectamente accesible y visualizado correctamente en dispositivos móviles (smartphones y tablets) adaptando rejillas (grids), tipografías, márgenes y modales según corresponda.
17. **Estándar del Asistente IA (Búsqueda y Propuesta Autónoma - ✨):** Todo botón o proceso destinado a buscar información, procesarla con LLMs y proponerla para autocompletar un formulario es un **Asistente IA**. Su comportamiento y diseño deben cumplir rigurosamente este patrón estructural y de flujo en 3 fases:
    - **Fase 1: Diseño y Ubicación del Botón:** Se colocará dentro de la pestaña activa, alineado a la izquierda (`justifyContent: 'flex-start'`). Su diseño base es Solid Purple (`linear-gradient(135deg, #8b5cf6, #6d28d9)`), texto blanco, negrita y sombra. Obligatoriamente incluye el emoji `✨` (ej. `✨ Asistente IA`). Durante la carga (`isAILoading`), el texto cambiará a un reloj de arena con contador en tiempo real (`⏳ Analizando... {segundos}s`), el cursor será `not-allowed` y el fondo pasará a tonos grises (`linear-gradient(135deg, #475569, #1e293b)`).
    - **Fase 2: Configuración Previa (Pre-Execution Modal):** NUNCA se debe ejecutar la petición a la IA directamente al hacer clic. OBLIGATORIAMENTE se abrirá un Modal Intermedio estructurado en varias partes diferenciadas:
      - **Encabezado (Header):** Tendrá el título `✨ Asistente IA` y utilizará **el mismo fondo degradado púrpura** del botón llamador (`linear-gradient(135deg, #8b5cf6, #6d28d9)`). A la derecha de este mismo encabezado se ubicarán los botones de acción: el botón de Cancelar y el botón de Activar el asistente (ej. `🚀 Analizar`).
      - **Contador Mensual de IA:** Debajo del encabezado se debe mostrar obligatoriamente el contador de interacciones IA consumidas del mes en curso obtenidas del servidor (ej. `Interacciones IA este mes: X / Y`), cambiando de color a rojo en caso de agotamiento del límite.
      - **Cuerpo (Body) - Estructura de 4 Apartados:**
        1. **Entidad Objetivo:** Bloque visual (solo lectura) indicando sobre qué elemento se buscará (ej. "🌱 Especie seleccionada: Tomate").
        2. **System Prompt Base:** Bloque colapsable (acordeón) con las instrucciones técnicas de sistema para la IA. Cerrado por defecto.
        3. **Prompt Dinámico (Texto Libre):** Un `textarea` editable. Mostrará dinámicamente en formato texto las categorías seleccionadas en el Apartado 4, permitiendo además al usuario añadir sus propias directrices libres. *(Principio de Eficiencia Dinámica: Al backend solo se enviarán las claves que el usuario haya dejado seleccionadas, descartando por completo el resto para ahorrar tokens y acelerar la respuesta).*
        4. **Ayudante de Categorías (Checkboxes):** Cuadrícula de checks con todas las categorías de datos. Interactúan como un "ayudante" del Apartado 3: al marcar/desmarcar un check, su nombre se añade o se elimina automáticamente del texto del `textarea`. La IA tomará como contexto de búsqueda final la consolidación de los apartados 1, 2 y 3.
      - **Estado de Carga Intermedio (Loading State — Patrón Overlay Atenuado):** Al pulsar Analizar, el modal **NO SE CERRARÁ NI CAMBIARÁ DE ASPECTO BRUSCAMENTE**. El Encabezado mutará suavemente: desaparecerán los botones y se mostrará un reloj de arena animado (`⏳ Analizando... {segundos}s`). El Cuerpo del modal **NO reemplazará** los 4 apartados; estos permanecerán visibles pero **atenuados** (`opacity: 0.3`, `pointerEvents: 'none'`, `transition: opacity 0.3s ease`). Sobre ellos se superpondrá un overlay semitransparente (`rgba(255,255,255,0.75)`, `position: absolute`) con un breve texto y pastillas/pills de color púrpura (`background: #ede9fe`, `color: #6d28d9`) indicando las categorías que la IA está consultando. Este patrón es idéntico al de la asimilación en la Fase 3 y queda **PROHIBIDO** reemplazar el contenido del body de golpe, ya que eso da sensación de "modal nuevo".
      - **Reset Obligatorio al Abrir:** Cada vez que se abre el Modal de Configuración Previa, se DEBEN resetear todas las categorías a seleccionadas (`true`) y limpiar el prompt dinámico libre, para que el usuario parta siempre de un estado limpio.
    - **Fase 3: Revisión de Propuestas (Diff Modal de 2 Columnas):** Cuando el Asistente IA termine de procesar (se cierra la Fase 2 y se abre esta Fase 3), es OBLIGATORIO no sobreescribir los datos directamente. Se debe transicionar a una vista de "Revisión de Propuestas" estructurada en **dos columnas** (grid con `Actual` a la izquierda y `Propuesta IA` a la derecha), evitando diseños lineales viejo ➡️ nuevo. Se diferenciarán visualmente los datos que cambian (amarillo/morado) de los que coinciden (gris). El usuario tendrá la libertad de incorporar los datos individualmente (checkboxes por campo), por grupos lógicos o en conjunto.
      - **Encabezado de Revisión (Header):** Contendrá obligatoriamente tres controles alineados a la derecha: (1) `⚠️ Ver solo cambios` (toggle checkbox), (2) `🗑️ Descartar` (botón rojo degradado `linear-gradient(135deg, #ef4444, #dc2626)`) y (3) `✅ Asimilar Todos` (botón verde degradado `linear-gradient(135deg, #10b981, #059669)`). Queda **PROHIBIDO** colocar estos botones en un footer inferior; deben estar siempre visibles en el header.
      - **Carga de Asimilación In-Situ (PROHIBICIÓN DE OVERLAYS):** Queda **TERMINANTEMENTE PROHIBIDO** abrir un modal, overlay o popup intermedio de pantalla completa durante la asimilación de datos. Cuando el usuario pulsa "Asimilar Todos" o cualquier acción de guardado masivo, el propio Encabezado del modal de revisión debe transicionar a un estado de carga: los botones desaparecen y se muestra un reloj de arena animado con contador (`⏳ Asimilando cambios... {segundos}s`), exactamente igual que en la Fase 2. El cuerpo del modal permanece visible pero inerte.
18. **Estándar del Botón de Chequeo (Diseño y Ubicación):** Todo formulario de edición o dashboard que incorpore un botón de "Chekeo" o "Ver Completado" para auditar el rellenado de campos, debe cumplir estrictamente este patrón visual:
    - **Ubicación:** Debe colocarse en una Barra de Acción Global (Action Bar Global) situada **debajo del subheader contextual (ej. el encabezado verde)** y **por encima de las pestañas de navegación**.
    - **Diseño del Botón (Solid Blue):** El estilo base debe ser fondo degradado azul (`background: 'linear-gradient(135deg, #0284c7, #0369a1)'`), texto blanco (`color: 'white'`), borde redondeado (`borderRadius: '8px'`), negrita (`fontWeight: 'bold'`), altura (`height: '38px'`), relleno (`padding: '0 16px'`) y sombra (`boxShadow: '0 4px 12px rgba(2, 132, 199, 0.2)'`).
    - **Estados e Iconografía:** Debe incluir obligatoriamente el emoji `🔍` al principio del texto (ej. `🔍 Chekeo`).
19. **Estándar de Formato de Fechas:** En cualquier lugar del programa (tablas, dashboards, modales, alertas, etc.), las fechas se mostrarán SIEMPRE en formato de Día, Mes y Año (ej. `DD/MM/YYYY`). Queda prohibido mostrar formatos crudos de base de datos o anglosajones de cara al usuario.
20. **Navegación Jerárquica Acumulativa (NORMA FUNDAMENTAL DE NAVEGACIÓN):** Cuando el usuario navega de una Página A a una Página B, la Página B **hereda la cadena de vuelta** de la siguiente manera obligatoria:
   - **Conserva todos sus propios botones** de navegación superiores intactos, adaptando su texto/destino al contexto de entrada si procede (ej. "Volver a Especies" → "Volver a Especies de Granja" cuando se viene desde un consumidor).
   - **Añade un botón extra** de vuelta al final de la botonera, con el **nombre específico y real** de la Página A de origen (ej. "🔙 Volver a Gallina", nunca genérico "Volver a Consumidor"). Este botón se implementa pasando los parámetros `?from=[modulo]&fromId=[id]&fromName=[nombre_codificado]` en la URL de navegación y leyéndolos con `useSearchParams()` en la página destino.
   - **La cadena es acumulativa:** la Página A ya tiene su propia botonera; al pulsar "Volver a [Página A]" se regresa a ella con todo su contexto intacto (filtros, scroll, estado colapsado) gracias a `router.push()` con el ID explícito.
   - **Reinicio al ir al Inicio:** El botón `🏠 Volver al Inicio` (que apunta a `/dashboard`) **rompe y reinicia la cadena** en su t