# LA BIBLIA - Verdantia (Normas Inquebrantables)

## Reglas de Oro
1. **Acceso Local:** Cuando se solicite "acceso local", iniciar únicamente el servidor en `localhost:3000`. **NUNCA** iniciar túneles (ngrok, pinggy, etc.) a menos que se pida de forma explícita.
2. **Canal de Despliegue Exclusivo (Modo Autónomo por Chat):** El asistente tiene el mandato y permiso total para asumir el control y automatizar el proceso de subida a producción. Si el usuario da la orden explícita mediante palabras clave como "SUBE A PRODUCCION", "sincroniza en GitHub" (o incluso variantes con errores de teclado como "SU(BE A PRODUCCION"), el agente ejecutará el despliegue íntegramente desde su propia terminal. Esto se hace para detectar y corregir cualquier error de código que surja durante la compilación (`npm run build`) en tiempo real.
   * **Integración con la Web:** Los botones del panel web están diseñados para copiar esta orden al portapapeles. El usuario solo debe pegar el comando en el chat para delegar la tarea al agente de forma segura.
   * **Protocolo de Despliegue:** Aunque lo haga el agente, se debe seguir el orden estricto de documentar en la Guía de Usuario, incrementar y estampar versión, compilar (corrigiendo fallos autónomamente si los hay), hacer commit, push a Git y desplegar en Firebase.
3. **Compatibilidad Next.js:** Prestar especial atención a las APIs y la estructura de archivos de la versión instalada de Next.js. Consultar los manuales de `node_modules/next/dist/docs/` ante cualquier cambio para evitar el uso de importaciones o funciones obsoletas.
4. **Refresco Automático y Efectivo (MANDATO INQUEBRANTABLE):** El asistente tiene la **OBLIGACIÓN ABSOLUTA E INELUDIBLE** de actualizar la página del navegador de forma automática cada vez que finalice una tarea o instrucción. **Cualquier cambio aplicado que no sea visualizado instantáneamente por el usuario es un FRACASO CRÍTICO.**
   - Si se modifican componentes React (`.tsx`), Next.js aplicará Hot Reload automáticamente.
   - Si Next.js no detecta el cambio o se editan archivos estáticos fuera del árbol principal (ej. `.md`, `.json`, `next.config.js`), el asistente **DEBE** forzar el refresco alterando el archivo principal implicado (ej. añadiendo un comentario temporal).
   - Si la caché de Turbopack se enquista y el usuario reporta que no ve los cambios, el asistente aplicará la purga nuclear de inmediato sin preguntar: `rm -r .next` y reiniciar `npm run dev`. ¡CERO EXCUSAS!
5. **Control de Copias de Seguridad (GitHub):** **NUNCA** extraerás ni descargarás una copia de seguridad de GitHub de forma espontánea o autónoma. Si por motivos de fuerza mayor consideras que es necesario restaurar o recurrir a una copia, **DEBES** pedir permiso explícito al usuario y explicar detalladamente el motivo y las consecuencias antes de ejecutar ninguna acción relacionada.
6. **Navegación Local y Pruebas de Navegador:** **NUNCA** realizarás navegación local ni abrirás/utilizarás el subagente de navegación del navegador (browser subagent) para comprobar páginas, realizar capturas de pantalla o realizar pruebas automáticas sin pedir permiso explícito al usuario antes de ejecutar dicha acción.
7. **Estándar de Dashboard de Muestra de Datos:** Todo dashboard destinado a listar o mostrar colecciones de datos (ej. catálogo de especies) debe basarse estrictamente en la ruta `/dashboard/admin/especies` y cumplir obligatoriamente estas características:
   - **Ancho Completo:** La vista debe ocupar el 100% del ancho (`width: '100%'`), sin restricciones de `maxWidth` ni centrados.
   - **Subheader Global:** Debe incluir un bloque superior con fondo degradado (`linear-gradient`) pertinente al módulo, conteniendo el Título (con Emoji) a la izquierda, y los botones de acción principal (Ej. `➕ Nuevo`) a la derecha. Los filtros rápidos (tags/píldoras) irán integrados en la parte inferior de este subheader.
   - **Carga sin Flickering (Overlay):** Queda prohibido desmontar la tabla al cargar o filtrar datos. Se debe usar un contenedor `position: 'relative'` y superponer un Overlay absoluto semitransparente (`rgba(255,255,255,0.65)`) con un spinner circular, mientras la tabla reduce su opacidad al 60%.
   - **Tabla Zebra y Botonera Estandarizada:** Las filas alternarán colores de fondo (`white` y `#f8fafc`). La columna de acciones a la derecha tendrá botones consistentes con sus códigos de color: Editar (Gris/Blanco), Inhabilitar (Amarillo), Eliminar (Rojo), Reactivar (Verde).
8. **Estándar de Dashboard de Edición de Datos:** Toda ruta de edición de formularios (ej. `/dashboard/admin/especies/[id]`) es el estándar maestro de edición y debe seguir obligatoriamente estos patrones:
   - **Ancho Completo:** La vista debe ocupar el 100% del ancho (`width: '100%'`), sin restricciones de `maxWidth` ni centrados.
   - **Navegación Hierárquica Superior:** Doble botonera alineada a la izquierda y situada en lo alto del DOM: `🏠 Volver al Inicio` y `🔙 Volver a [Listado Global]`. Quedan prohibidos los botones de 'Volver' redundantes a pie de página.
   - **Subheader Contextual y Autoguardado:** Debajo de la navegación mostrará el título de edición. El guardado de datos será **automático** (Auto-Save con debounce al detectar cambios en los inputs), eliminando la necesidad de un botón manual de "Guardar Cambios". Se usará un pequeño indicador visual de estado (ej. "Guardando..." o "Guardado").
   - **Pestañas Controladas por CSS:** Queda tajantemente prohibido usar renderizado condicional de React para las pestañas de contenido. Todas las pestañas deben estar renderizadas siempre en el DOM y se ocultarán exclusivamente mediante CSS (`display: none / block` o `grid`) para precargar los datos en segundo plano sin parpadeos.
   - **Multimedia Segregado:** Prohibido agrupar fotos y documentos bajo una pestaña "Adjuntos". Obligatorio separarlo en pestañas independientes `📷 Fotos` y `📄 PDFs`, instanciando siempre el gestor `VariedadMediaManager`.
   - **Edición en Línea (Grids):** Cualquier colección secundaria anidada debe gestionarse a través de listas/tablas editables en línea sin requerir ventanas modales externas.
9. **Estándar Fotográfico y Multimedia (Hero Carousel & Galerías):** Cualquier módulo que gestione fotografías en los dashboards de edición debe cumplir esta arquitectura estricta:
   - **Hero Carousel (Encabezado Visual):** Situado debajo del Subheader contextual. Debe tener un fondo degradado basado en el color vibrante (extraído por IA). Contendrá la Foto Principal (Hero) a tamaño `180px x 220px` (proporción 3:4) aplicando todos los metadatos JSON de encuadre/zoom/brillo.
   - **Miniaturas Apiladas (Verticales):** Al lado de la foto Hero, se apilarán **verticalmente** un máximo de 3 miniaturas de `52px x 70px`. No heredarán el zoom del Hero para no cortar caras (usarán encuadre neutral `cover`). Su interactividad se marca solo con hover (borde morado y escala), sin añadir textos redundantes como "Haz clic para cambiar".
   - **Sincronización Inmediata:** Cualquier acción en la galería inferior (añadir, borrar, reordenar) disparará el callback `onMediaChange` que actualizará automáticamente el Hero Carousel sin recargas de página.
   - **Galería (Pestaña Fotos):** Incorpora el motor Dropzone, renderización instantánea con BlurHash y botones de acción unificados (Estrella=Portada, Lápiz=Editar, X=Eliminar).
   - **Editor Visual Estándar:** El modal de edición fotográfica forzará la proporción 3:4 y soportará Drag-to-Pan (arrastre libre) y sliders de Zoom, Brillo y Contraste, persistiendo los datos en un objeto JSON (`resumen`). Contará con botón "Auto Color" y "Smart Save".
10. **Estándar de Asistentes de Datos (Wizards de Completado):** Todo proceso secuencial de recolección de datos (ej. Asistente de Semillas, Asistente de Cultivos o Onboarding) debe implementarse como un Modal estructurado bajo las siguientes directrices obligatorias:
   - **Flujo en Cascada (Cascading Flow):** Queda prohibida la navegación por "páginas" aisladas. A medida que el usuario avanza de paso, el paso anterior debe colapsar visualmente convirtiéndose en un bloque de resumen (con un check verde `✅`, fondo suave y botón de `Cambiar`). El nuevo paso activo se renderizará debajo, ligeramente sangrado (con `marginLeft`), creando una jerarquía visual continua.
   - **Selectores Visuales (Cards) y Emojis:** Las opciones a elegir (hortalizas, variedades, origen) jamás deben ser `<select>` nativos genéricos. Deben mostrarse como tarjetas interactivas en `grid`, con hover effects (elevación y cambio de borde) y siempre acompañadas de Emojis, iconos o fotos (vía BlurHash/media-url).
   - **Indicadores de Progreso y Explicaciones:** El Subheader del modal debe indicar claramente el paso actual (`Paso X de Y`). Si se solicitan datos complejos, se deben usar bloques explicativos (ej. `¿Por qué pedimos esto?` en cajas con borde izquierdo coloreado).
   - **Confirmación y Pantalla de Éxito:** El último paso activo debe ser siempre un resumen visual de lo seleccionado antes de enviar. Al confirmar, el formulario debe ser sustituido temporalmente por una pantalla de éxito conteniendo un Emoji gigante (ej. `🎉`) antes de que el modal se cierre solo mediante un `setTimeout`.
11. **Restauración de Estado (Botón Volver):** Al entrar a un dashboard, si volvemos a salir de él por medio del botón de vuelta atrás que está en la parte superior encima del encabezado, volveremos al sitio donde estábamos; si era un desplegable o fila expandida, esta estará desplegada, los filtros y pestañas activos se mantendrán seleccionados, el scroll se restaurará a su posición anterior, y el foco visual y/o de teclado irá exactamente al mismo sitio (resaltando la fila o elemento interactuado). Usa `sessionStorage` y `useEffect` en Next.js para persistir el scroll, filtros activos, foco y los estados `isExpanded` / `showDetalle`. Cualquier acceso directo desde el desplegable del menú lateral del superadministrador (por ejemplo, al entrar a la sección de Análisis de Dashboard) se considerará una entrada limpia y se deben anular y limpiar los filtros cargándolos en su estado inicial por defecto (ej. 'all').
12. **Protocolo de Despliegue a Producción:** Antes de ejecutar comandos de despliegue a producción, es OBLIGATORIO: (1) Incrementar la versión en package.json. (2) Actualizar la fecha/hora y versión visible en la landing page (src/app/page.tsx). NUNCA desplegar sin hacer el bump de versión antes.
13. **Protocolo de Refactorizacion Completa de Dashboards:** Cuando se refactoriza un dashboard monolítico (>500 líneas), la refactorización DEBE hacerse en un ÚNICO paso completo, sin medias tintas. El resultado final OBLIGATORIO es un page.tsx de menos de 150 líneas que solo contenga orquestación. El proceso completo es:
   - **Paso 1 - Hooks (lógica de negocio):** Extraer TODO el estado y los handlers a hooks personalizados en una carpeta hooks/ adyacente al page.tsx. Cada dominio funcional tiene su propio hook (ej. usePendientes.ts, useRechazos.ts, usePhotoEditor.ts).
   - **Paso 2 - Componentes (JSX):** Extraer TODOS los bloques de JSX de más de 20 líneas a componentes reutilizables en una carpeta components/ adyacente. Esto incluye: tarjetas de usuario, modales de confirmación, overlays de foto (lightbox), editores visuales, cabeceras, paneles de tabs. NINGÚN bloque JSX extenso puede quedarse inline en el page.tsx.
   - **Paso 3 - Servicios (API):** Extraer todas las llamadas fetch() a un archivo de servicio services/[nombre]Api.ts. El page.tsx y los hooks NO deben contener fetch() directos.
   - **Paso 4 - page.tsx final:** El page.tsx resultante debe ser EXCLUSIVAMENTE un orquestador: importa hooks, importa componentes y los ensambla. Cero lógica de negocio, cero fetch(), cero bloques JSX extensos inline.
   - **Verificación:** Tras la refactorización, el page.tsx debe tener menos de 150 líneas. Si tiene más, la refactorización está INCOMPLETA.
   - **Actualización del contador:** Después de refactorizar, actualizar el número de líneas correspondiente en la tabla de Análisis de Código de mantenimiento/page.tsx para que refleje el valor real.
14. **Marca de Agua y SEO en Imágenes (MANDATO SEO Y MARCA):** Todas las imágenes del blog, galerías o generadas por IA deben llevar de manera obligatoria la marca de agua translúcida de 'VERDANTIA' en la esquina inferior derecha. Asimismo, es imperativo que cada imagen disponga de descripciones de posicionamiento SEO (atributos `alt` y `title` detallados) tanto en la base de datos (dentro del JSON de contenido o campos dedicados) como en el renderizado del código para asegurar un correcto posicionamiento orgánico.
15. **Estándar de Artículos de Blog Generados por IA (AI Blog Standard):** Todo artículo de blog que sea generado mediante los asistentes de Inteligencia Artificial del sistema (por ejemplo, en base a especies, labores o documentos cargados) debe estructurarse rigurosamente bajo el estándar modular definido en `BLOG_STANDARD.md` y `generate-blog/route.ts`. Esto incluye:
    - **Estructura en Bloques Obligatorios:** Encabezado (título interrogativo SEO, resumen, tags, autor y fecha), Ficha Rápida (grid 2x3 con exactamente 6 métricas clave e iconos), Introducción (máx 100 palabras con gancho), Secciones alternadas (H2 + Markdown + fotos alineadas a la derecha o izquierda), Caja de Consejos (con fondo ámbar y borde izquierdo naranja) y un bloque CTA con botones de acción.
    - **Imágenes del Pipeline:** Generación de exactamente 3 imágenes mediante Imagen 4.0, aplicando obligatoriamente el redimensionamiento, conversión a formato WebP/PNG optimizado, marca de agua en la esquina inferior derecha y almacenamiento en Firebase Storage vinculando la metadata en `datosadjuntos`.
    - **Reglas de Redacción:** Párrafos concisos de máximo 3 líneas (sin paja), uso de negritas para destacar conceptos y datos numéricos exactos (temperaturas, marcos de plantación, etc.), manteniendo un tono cercano, profesional y agronómico.
16. **Diseño Responsive para Dashboards:** Al diseñar y desarrollar dashboards y formularios, se tendrá siempre en cuenta el concepto de diseño responsivo. Queda prohibido diseñar interfaces exclusivas para resoluciones de escritorio; cualquier formulario o panel de visualización de datos debe ser perfectamente accesible y visualizado correctamente en dispositivos móviles (smartphones y tablets) adaptando rejillas (grids), tipografías, márgenes y modales según corresponda.
