const fs = require('fs');
const file = 'src/components/admin/EspecieForm.tsx';
let content = fs.readFileSync(file, 'utf8');

// 1. Change selectedRels type from string[] to any[]
content = content.replace(
  "const [selectedRels, setSelectedRels] = useState<{ ben: string[], per: string[], pla: string[] }>({ ben: [], per: [], pla: [] });",
  "const [selectedRels, setSelectedRels] = useState<{ ben: any[], per: any[], pla: any[] }>({ ben: [], per: [], pla: [] });"
);

// 2. Update the modal checkboxes to handle objects - Beneficiosas
content = content.replace(
  `{aiProposal.asociaciones_beneficiosas.map((name: string) => {\r\n                            const exists = masterEspecies.some(e => e.especiesnombre.toLowerCase().trim() === name.toLowerCase().trim());\r\n                            return (\r\n                              <li key={name} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '4px 0' }}>\r\n                                <input type="checkbox" checked={selectedRels.ben.includes(name)} onChange={(e) => {\r\n                                  if (e.target.checked) setSelectedRels(p => ({...p, ben: [...p.ben, name]}));\r\n                                  else setSelectedRels(p => ({...p, ben: p.ben.filter(n => n !== name)}));\r\n                                }} style={{ width: '16px', height: '16px', accentColor: '#10b981', cursor: 'pointer' }} />\r\n                                <span>{exists ? '✅' : '➕'}</span>\r\n                                <span>{name}</span> {exists ? <small style={{color: '#64748b'}}>(Existente)</small> : <small style={{color: '#f59e0b'}}>(Se creará inactiva)</small>}\r\n                              </li>\r\n                            );\r\n                          })}`,
  `{aiProposal.asociaciones_beneficiosas.map((item: any) => {\r\n                            const name = typeof item === 'string' ? item : item?.nombre;\r\n                            const motivo = typeof item === 'string' ? '' : (item?.motivo || '');\r\n                            if (!name) return null;\r\n                            const exists = masterEspecies.some(e => e.especiesnombre.toLowerCase().trim() === name.toLowerCase().trim());\r\n                            const isChecked = selectedRels.ben.some((s: any) => (typeof s === 'string' ? s : s?.nombre) === name);\r\n                            return (\r\n                              <li key={name} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '4px 0' }}>\r\n                                <input type="checkbox" checked={isChecked} onChange={(e) => {\r\n                                  if (e.target.checked) setSelectedRels(p => ({...p, ben: [...p.ben, item]}));\r\n                                  else setSelectedRels(p => ({...p, ben: p.ben.filter((n: any) => (typeof n === 'string' ? n : n?.nombre) !== name)}));\r\n                                }} style={{ width: '16px', height: '16px', accentColor: '#10b981', cursor: 'pointer' }} />\r\n                                <span>{exists ? '✅' : '➕'}</span>\r\n                                <div><span style={{fontWeight: 'bold'}}>{name}</span>{motivo ? <span style={{color: '#64748b', fontSize: '0.85rem'}}> — {motivo}</span> : ''} {exists ? <small style={{color: '#64748b'}}>(Existente)</small> : <small style={{color: '#f59e0b'}}>(Se creará inactiva)</small>}</div>\r\n                              </li>\r\n                            );\r\n                          })}`
);

// 3. Update Perjudiciales checkboxes
content = content.replace(
  `{aiProposal.asociaciones_perjudiciales.map((name: string) => {\r\n                            const exists = masterEspecies.some(e => e.especiesnombre.toLowerCase().trim() === name.toLowerCase().trim());\r\n                            return (\r\n                              <li key={name} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '4px 0' }}>\r\n                                <input type="checkbox" checked={selectedRels.per.includes(name)} onChange={(e) => {\r\n                                  if (e.target.checked) setSelectedRels(p => ({...p, per: [...p.per, name]}));\r\n                                  else setSelectedRels(p => ({...p, per: p.per.filter(n => n !== name)}));\r\n                                }} style={{ width: '16px', height: '16px', accentColor: '#ef4444', cursor: 'pointer' }} />\r\n                                <span>{exists ? '✅' : '➕'}</span>\r\n                                <span>{name}</span> {exists ? <small style={{color: '#64748b'}}>(Existente)</small> : <small style={{color: '#f59e0b'}}>(Se creará inactiva)</small>}\r\n                              </li>\r\n                            );\r\n                          })}`,
  `{aiProposal.asociaciones_perjudiciales.map((item: any) => {\r\n                            const name = typeof item === 'string' ? item : item?.nombre;\r\n                            const motivo = typeof item === 'string' ? '' : (item?.motivo || '');\r\n                            if (!name) return null;\r\n                            const exists = masterEspecies.some(e => e.especiesnombre.toLowerCase().trim() === name.toLowerCase().trim());\r\n                            const isChecked = selectedRels.per.some((s: any) => (typeof s === 'string' ? s : s?.nombre) === name);\r\n                            return (\r\n                              <li key={name} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '4px 0' }}>\r\n                                <input type="checkbox" checked={isChecked} onChange={(e) => {\r\n                                  if (e.target.checked) setSelectedRels(p => ({...p, per: [...p.per, item]}));\r\n                                  else setSelectedRels(p => ({...p, per: p.per.filter((n: any) => (typeof n === 'string' ? n : n?.nombre) !== name)}));\r\n                                }} style={{ width: '16px', height: '16px', accentColor: '#ef4444', cursor: 'pointer' }} />\r\n                                <span>{exists ? '✅' : '➕'}</span>\r\n                                <div><span style={{fontWeight: 'bold'}}>{name}</span>{motivo ? <span style={{color: '#64748b', fontSize: '0.85rem'}}> — {motivo}</span> : ''} {exists ? <small style={{color: '#64748b'}}>(Existente)</small> : <small style={{color: '#f59e0b'}}>(Se creará inactiva)</small>}</div>\r\n                              </li>\r\n                            );\r\n                          })}`
);

// 4. Update Plagas checkboxes
content = content.replace(
  `{aiProposal.plagas_asociadas.map((name: string) => {\r\n                            const exists = masterPlagas.some(p => p.plagasnombre.toLowerCase().trim() === name.toLowerCase().trim());\r\n                            return (\r\n                              <li key={name} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '4px 0' }}>\r\n                                <input type="checkbox" checked={selectedRels.pla.includes(name)} onChange={(e) => {\r\n                                  if (e.target.checked) setSelectedRels(p => ({...p, pla: [...p.pla, name]}));\r\n                                  else setSelectedRels(p => ({...p, pla: p.pla.filter(n => n !== name)}));\r\n                                }} style={{ width: '16px', height: '16px', accentColor: '#f97316', cursor: 'pointer' }} />\r\n                                <span>{exists ? '✅' : '➕'}</span>\r\n                                <span>{name}</span> {exists ? <small style={{color: '#64748b'}}>(Existente)</small> : <small style={{color: '#f59e0b'}}>(Se creará inactiva)</small>}\r\n                              </li>\r\n                            );\r\n                          })}`,
  `{aiProposal.plagas_asociadas.map((item: any) => {\r\n                            const name = typeof item === 'string' ? item : item?.nombre;\r\n                            const notas = typeof item === 'string' ? '' : (item?.notas || '');\r\n                            if (!name) return null;\r\n                            const exists = masterPlagas.some(p => p.plagasnombre.toLowerCase().trim() === name.toLowerCase().trim());\r\n                            const isChecked = selectedRels.pla.some((s: any) => (typeof s === 'string' ? s : s?.nombre) === name);\r\n                            return (\r\n                              <li key={name} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '4px 0' }}>\r\n                                <input type="checkbox" checked={isChecked} onChange={(e) => {\r\n                                  if (e.target.checked) setSelectedRels(p => ({...p, pla: [...p.pla, item]}));\r\n                                  else setSelectedRels(p => ({...p, pla: p.pla.filter((n: any) => (typeof n === 'string' ? n : n?.nombre) !== name)}));\r\n                                }} style={{ width: '16px', height: '16px', accentColor: '#f97316', cursor: 'pointer' }} />\r\n                                <span>{exists ? '✅' : '➕'}</span>\r\n                                <div><span style={{fontWeight: 'bold'}}>{name}</span>{notas ? <span style={{color: '#64748b', fontSize: '0.85rem'}}> — {notas}</span> : ''} {exists ? <small style={{color: '#64748b'}}>(Existente)</small> : <small style={{color: '#f59e0b'}}>(Se creará inactiva)</small>}</div>\r\n                              </li>\r\n                            );\r\n                          })}`
);

fs.writeFileSync(file, content);
console.log('Modal checkboxes updated for objects with motivo/notas.');
